export const CandidateTypes = Object.freeze({
    ADD_CANDIDATE: 'ADD_CANDIDATE',
    EDIT_CANDIDATE: 'EDIT_CANDIDATE',
    DELETE_CANDIDATE: 'DELETE_CANDIDATE',
    SET_CANDIDATES: 'SET_CANDIDATES'
})