export const ElectionTypes = Object.freeze({
    CREATE_ELECTION: 'CREATE_ELECTION',
    EDIT_ELECTION: 'EDIT_ELECTION',
    DELETE_ELECTION: 'DELETE_ELECTION',
    CURRENT_ELECTION: 'CURRENT_ELECTION',
    SET_ELECTIONS: 'SET_ELECTIONS'
})